import { DevicePreset, WeaponGuide, SensitivityConfig } from '../types';

export const DEVICE_PRESETS: DevicePreset[] = [
  {
    id: 'budget_android',
    name: 'Redmi / Realme / Vivo (2GB - 4GB RAM)',
    category: 'low_end',
    ram: '2GB - 4GB',
    screenHz: '60Hz',
    descriptionHi: 'लो-एंड फोन के लिए हाई सेंसिटिविटी ताकि स्क्रीन पर ड्रैग आसानी से हो और रिकॉइल कंट्रोल रहे।',
    descriptionEn: 'High sensitivity configuration for budget devices to ensure responsive drag speed without frame drag.',
    recommendedDpi: 440,
    bestButtonSize: 45,
    defaultSens: {
      general: 100,
      redDot: 98,
      scope2x: 95,
      scope4x: 92,
      sniperScope: 55,
      freeLook: 70,
      fireButtonSize: 45,
      dpi: 440,
      touchResponse: 'Fast (100ms)',
      pointerSpeed: 10,
    },
  },
  {
    id: 'mid_android',
    name: 'Poco / Samsung / OnePlus (6GB - 8GB RAM)',
    category: 'mid_range',
    ram: '6GB - 8GB',
    screenHz: '90Hz / 120Hz',
    descriptionHi: 'मिड-रेंज 90Hz/120Hz स्क्रीन के लिए बैलेंस्ड सेटिंग ताकि एम हेड पर लॉक हो और हवा में गोली न उड़े।',
    descriptionEn: 'Balanced head-lock calibration for 90Hz/120Hz devices preventing over-drag above the enemy head.',
    recommendedDpi: 410,
    bestButtonSize: 48,
    defaultSens: {
      general: 94,
      redDot: 92,
      scope2x: 88,
      scope4x: 85,
      sniperScope: 50,
      freeLook: 65,
      fireButtonSize: 48,
      dpi: 410,
      touchResponse: 'Ultra-Fast (60ms)',
      pointerSpeed: 8,
    },
  },
  {
    id: 'flagship_android',
    name: 'iQOO / ROG Phone / Samsung S Series (12GB+ RAM)',
    category: 'flagship',
    ram: '12GB+ / Snapdragon 8 Gen',
    screenHz: '120Hz - 165Hz',
    descriptionHi: 'हाई टच सैंपलिंग रेट और 144Hz डिस्प्ले के लिए परफेक्ट स्मूथ रेड नंबर्स कैलिब्रेशन।',
    descriptionEn: 'Esports-grade smooth calibration tuned for 360Hz+ touch sampling rate and Snapdragon flagships.',
    recommendedDpi: 392,
    bestButtonSize: 52,
    defaultSens: {
      general: 89,
      redDot: 86,
      scope2x: 82,
      scope4x: 78,
      sniperScope: 45,
      freeLook: 60,
      fireButtonSize: 52,
      dpi: 392,
      touchResponse: 'Instant (30ms)',
      pointerSpeed: 7,
    },
  },
  {
    id: 'apple_iphone',
    name: 'Apple iPhone (iPhone 11 - 16 Pro Max / iPad)',
    category: 'ios',
    ram: 'iOS A-Bionic / ProMotion',
    screenHz: '120Hz ProMotion',
    descriptionHi: 'iOS 3D/Haptic Touch और प्रोमोशन डिस्प्ले के लिए स्पेशल हेड-लॉक सेंसिटिविटी।',
    descriptionEn: 'Fine-tuned for iOS smooth capacitive touch response and ProMotion 120Hz refresh rate.',
    recommendedDpi: 0, // No DPI on iOS, pointer speed in AssistiveTouch
    bestButtonSize: 44,
    defaultSens: {
      general: 85,
      redDot: 82,
      scope2x: 76,
      scope4x: 74,
      sniperScope: 42,
      freeLook: 58,
      fireButtonSize: 44,
      dpi: 0,
      touchResponse: 'ProMotion Haptic',
      pointerSpeed: 7,
    },
  },
  {
    id: 'pc_emulator',
    name: 'PC Emulator (BlueStacks 5 / MSI / LDPlayer)',
    category: 'pc',
    ram: 'Mouse & Keyboard X/Y',
    screenHz: '144Hz - 240Hz',
    descriptionHi: 'माउस DPI 800/1200 और एमुलेटर X/Y सेंसिटिविटी ताकि 360 ड्रैग मक्खन की तरह लगे।',
    descriptionEn: 'PC Mouse DPI & X/Y tweaking values for zero recoil and flick one-taps.',
    recommendedDpi: 800,
    bestButtonSize: 35,
    defaultSens: {
      general: 65,
      redDot: 70,
      scope2x: 62,
      scope4x: 58,
      sniperScope: 38,
      freeLook: 50,
      fireButtonSize: 35,
      dpi: 800,
      touchResponse: 'Mouse Polling 1000Hz',
      pointerSpeed: 6,
    },
  },
];

export const WEAPON_GUIDES: WeaponGuide[] = [
  {
    id: 'shotgun',
    name: 'Shotguns (वन-टैप किंग)',
    iconWeapon: 'M1887 & M1014',
    popularGuns: ['M1887 (Double Barrel)', 'M1014', 'MAG-7', 'SPAS-12'],
    dragTechniqueHi: 'तेज स्ट्रेट ड्रैग (Fast Straight Drag): फायर बटन को नीचे से ऊपर की ओर तुरंत झटके से खींचें। क्लोज रेंज में सबसे बेस्ट काम करता है।',
    dragTechniqueEn: 'Fast Straight Up Drag: Flick the fire button aggressively upwards from the base. Best for close-quarter instant red crits.',
    sensBoost: {
      general: 99,
      redDot: 95,
      fireButtonSize: 46,
    },
  },
  {
    id: 'smg',
    name: 'SMG (रेड स्प्रे लॉक)',
    iconWeapon: 'MP40 & UMP',
    popularGuns: ['MP40', 'UMP (Armor Penetration)', 'Thompson', 'MP5-X'],
    dragTechniqueHi: 'स्मूथ रोटेशन ड्रैग (Smooth J-Drag): अगर दुश्मन भाग रहा है तो फायर बटन को उसके सिर की दिशा में हल्का घुमाकर (J शेप में) खींचें।',
    dragTechniqueEn: 'Rotation J-Shape Drag: Pull the fire button in a slight curve towards the direction the enemy is sprinting.',
    sensBoost: {
      general: 95,
      redDot: 98,
      scope2x: 90,
      fireButtonSize: 48,
    },
  },
  {
    id: 'pistol',
    name: 'One-Tap Pistols (क्लैश स्क्वाड)',
    iconWeapon: 'Desert Eagle & M500',
    popularGuns: ['Desert Eagle', 'M500 (Red Dot Scope)', 'USP-2', 'G18'],
    dragTechniqueHi: 'सिट-अप या स्टेबल वन-टैप: पहले एम को दुश्मन के कंधे के पास रखें (व्हाइट एम), फिर तेजी से हेड की तरफ ड्रैग करें (100% रेड नंबर)।',
    dragTechniqueEn: 'White-to-Red Flick: Position crosshair near neck/chest while white, flick up smoothly for 495+ red crit damage.',
    sensBoost: {
      general: 100,
      redDot: 100,
      fireButtonSize: 44,
    },
  },
  {
    id: 'ar',
    name: 'AR / Marksman (लॉन्ग रेंज)',
    iconWeapon: 'Woodpecker & AK47',
    popularGuns: ['Woodpecker', 'SVD-Y', 'AK47', 'M4A1-III', 'SCAR'],
    dragTechniqueHi: 'कंट्रोल्ड स्लो ड्रैग: ज्यादा तेज ड्रैग न करें, मीडियम स्पीड से ऊपर खींचें ताकि एम सिर पर चिपक जाए और रिक्वायल न बने।',
    dragTechniqueEn: 'Controlled Mid Drag: Pull up with moderate speed and pause right as crosshair turns red at head level.',
    sensBoost: {
      general: 92,
      redDot: 90,
      scope4x: 86,
      fireButtonSize: 50,
    },
  },
  {
    id: 'sniper',
    name: 'Sniper Rifles (क्विक स्कोप)',
    iconWeapon: 'AWM & M82B',
    popularGuns: ['AWM', 'M82B (Barrett)', 'Kar98k', 'Trogon'],
    dragTechniqueHi: 'डबल स्नाइपर स्विचिंग: स्कोप ओपन -> फायर -> तुरंत गन स्विच -> री-एम। स्नाइपर स्कोप सेंसिटिविटी 45-55 सबसे सटीक रहती है।',
    dragTechniqueEn: 'Quick Scope & Switch: Scope -> Fire -> Instant Gun Switch. Keep sniper sensitivity around 45-55 for steady tracking.',
    sensBoost: {
      general: 88,
      sniperScope: 50,
      fireButtonSize: 54,
    },
  },
];

export const PRO_TIPS = {
  hi: [
    {
      title: 'फायर बटन साइज (Fire Button Size)',
      text: 'फायर बटन को हमेशा 44% से 50% के बीच रखें। बहुत बड़ा बटन स्क्रीन पर ऊपर खींचने की जगह नहीं छोड़ता, और बहुत छोटा मिसक्लिक करवाता है।',
    },
    {
      title: 'फायर बटन की सही पोजीशन (Positioning)',
      text: 'फायर बटन को स्क्रीन के निचले आधे हिस्से में थोड़ा नीचे रखें ताकि आपके अंगूठे को ऊपर की तरफ स्वाइप करने के लिए पूरी जगह (Runway) मिले।',
    },
    {
      title: 'व्हाइट एम तकनीक (White Aim Drag)',
      text: 'फायर करने से पहले एम को दुश्मन के शरीर पर न चिपकाएं (रेड एम)। एम को दुश्मन के थोड़ा साइड या पैरों के पास व्हाइट रखें और फिर सीधे हेड पर ड्रैग करें।',
    },
    {
      title: 'DPI (स्मालेस्ट विड्थ) कैसे सेट करें',
      text: 'Settings -> Developer Options -> Smallest Width (DPI)। इसे कभी भी 500 से ऊपर न बढ़ाएं। 411 से 460 DPI फोन के लिए सबसे सुरक्षित और स्मूथ है।',
    },
    {
      title: 'फेक इंजेक्टर / हैक से बचें (Anti-Ban Warning)',
      text: 'कोई भी 3rd party apk या config फ़ाइल आपकी Free Fire ID को 10 साल के लिए बैन करवा सकती है। असली प्रो प्लेयर्स हमेशा लीगल सेंसिटिविटी + ड्रैग तकनीक का इस्तेमाल करते हैं!',
    },
  ],
  en: [
    {
      title: 'Optimal Fire Button Size',
      text: 'Keep your Fire Button size between 44% and 50%. A button that is too large reduces drag runway; too small causes missed taps during hectic fights.',
    },
    {
      title: 'Fire Button Placement',
      text: 'Place your Fire Button lower down on the right side. This gives your thumb maximum physical runway to flick upwards without hitting the top bezel.',
    },
    {
      title: 'White Aim Flick Technique',
      text: 'Keep crosshair white (outside enemy silhouette) near the chest/neck level, then flick sharply toward the head for instant 100% red damage.',
    },
    {
      title: 'Safe DPI (Smallest Width) Range',
      text: 'Go to Settings -> Developer Options -> Smallest Width. Recommended: 411 to 460. Never exceed 500 on budget phones to prevent black screen issues.',
    },
    {
      title: '100% Safe & Anti-Ban Notice',
      text: 'Third-party injectors and modded APKs violate Free Fire terms and trigger permanent device IMEI bans. Legitimate sensitivity calibration is 100% safe & esports approved.',
    },
  ],
};
